### ISSUE TITLE
Junyuan Chen Weekly Scrum- 03/07/2021 to 03/12/2021

### ISSUE THREAD

**Issue by chenjunyuan1998** [XinruiLi0/SYSC4806-Project#1]
what have I done this week?
Model Implementation 
Controller Implementation 
Repo Implementation

what will I do next week?
Add more features in Back-End Part to make the project more graceful (error handling/input restriction)

what is holding me back?
nothing

**Comment by chenjunyuan1998** [comment]
03/09/2021 Model and Controller done for the prototype of milestone 1 (basic services)

**Comment by chenjunyuan1998** [comment]
03/10/2021 Added new feature to Web Controller to support Ajax request and now added method for search the result. And new toString method for searching

**Comment by chenjunyuan1998** [comment]
03/10/2021 Updated model controller to support feature

**Comment by chenjunyuan1998** [comment]
Week 03/07/2021 work done.

**Comment by xilingdc** [comment]
well done
