### ISSUE TITLE
Weekly Scrum - 03/16/2021 to 03/27/2021

### ISSUE THREAD

**Issue by XinruiLi0** [XinruiLi0/SYSC4806-Project#46]

**Comment by XinruiLi0** [comment]
The database is set up on the local server.

**Comment by XinruiLi0** [comment]
Setup the database connection configuration and create a method to execute SQL query in Back-End. https://github.com/XinruiLi0/SYSC4806-Project/issues/44

**Comment by chenjunyuan1998** [comment]
Update Back-end Search method to associate with database

**Comment by chenjunyuan1998** [comment]
Added new feature update questionnaire for return user and correspond part in front end

**Comment by acrophobeee** [comment]
Modify the HTML page, add the support for VUE.js

**Comment by acrophobeee** [comment]
Update the back-end add questionnaire method, make it works for database

**Comment by xilingdc** [comment]
update front-end

**Comment by xilingdc** [comment]
update javadoc, class diagram, readme
